name: test

on: push
jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        deno: [v1.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Lint
        run: |
          deno fmt --check
          deno lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        deno: [v1.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Test
        run: deno task test
